name: Build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    uses: FuckAPK/workflows/.github/workflows/build.yml@main
    permissions:
      contents: write
    secrets:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
